# Generated by Django 4.2 on 2025-11-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_comentario_autor_alter_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='categoria',
            field=models.CharField(choices=[('astronomia', 'Astronomía'), ('tecnologia', 'Tecnología'), ('salud', 'Salud'), ('historia', 'Historia'), ('entretenimiento', 'Entretenimiento'), ('gastronomia', 'Gastronomía')], default='astronomia', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('astronomia', 'Astronomía'), ('tecnologia', 'Tecnología'), ('salud', 'Salud'), ('historia', 'Historia'), ('entretenimiento', 'Entretenimiento'), ('gastronomia', 'Gastronomía')], default='astronomia', max_length=30),
            preserve_default=False,
        ),
    ]
